### ISSUE TITLE
quantmerge on genes is truncating output

### ISSUE THREAD

**Issue by cljacobs** [COMBINE-lab/salmon#356] opened 2019-04-10 23:59 UTC
Salmon version: 0.13.1 (installed via pre-compiled binary)

I used salmon to quantify some samples and wanted to use the `quantmerge` command to produce a combined table. However, the merged table I got as output only contained 17 lines (of 52228 in the quant.genes.sf files).

I was able to identify that the problem was related somehow to the "Name" column itself, although I didn't find any obvious pattern for failure. For example, if I rename all the genes to simply "1", "2", ... and then `quantmerge`, I get a properly combined table with all samples/genes.

Looking back at the "original" data with the gene names, I find that the truncated merged table consistently/always truncates immediately *after* processing some gene names. For example, the 16th gene name in my "quant.genes.sf" table happens to be "Erdr1". If this line is moved to the top of that file, then the merged table will truncate at 2 (the header counting for one of those, obviously).

Unfortunately, it's not just "Erdr1". If that line is moved to the end of the file, or deleted entirely, there is another failure at gene "Gm28674", which happens to be the 19th gene. And so on for a very large number of names (I gave up after removing ~30 one at a time).

I've now tested with a few different samples and with a number of randomly selected subsets of the original quant files and the behavior is consistent. I can't figure out what the pattern is, but "Erdr1",  "Gm28674", and all the other genes I discovered with my ad-hoc process above, always cause `quantmerge` to truncate the output.

**Comment by rob-p** [comment] 2019-04-11 00:12
Hi @cljacobs,

  Can you share a small example that reproduces the issue?  Specifically, a few quants and the txp to gene mapping that you are using when you see the truncation?

Thanks,
Rob

**Comment by cljacobs** [comment] 2019-04-11 00:52
Sure thing. Here's a small quants file. It's just the top 2500 lines of one of the files I was testing with. I double checked and this one gets cut at 17 lines (it has "Erdr1").

[quant.genes.sf.txt](https://github.com/COMBINE-lab/salmon/files/3066421/quant.genes.sf.txt)

And here is the mapping I was using:

[map.tsv.gz](https://github.com/COMBINE-lab/salmon/files/3066425/map.tsv.gz)

If you need anything else, I'm happy to oblige.

**Comment by rob-p** [comment] 2019-04-11 01:00
Thanks for the quick reply; ill look into this asap and let you know what i find.

**Comment by rob-p** [comment] 2019-04-11 02:55
Hi @cljacobs,

  Ok, so I figured it out and just pushed a fix to develop.  The problem is the following.  The `--genes` flag was only recently added to quant merge (actually, via a pull request).  The problem is that while, in transcript-level `quant.sf` files, the `Length` field is always an integer, in gene-level `quant.genes.sf` files, the `Length` field can actually be a floating point number (because the gene length is the abundance weighted combination of transcript lengths).  So the problem is that the code was parsing length as a `uint32_t`, which is right for transcript-level files but wrong for gene-level files (where it should be a `double`).  This caused the parsing to fail when aggregating gene-level files in your example data. As I said, I pushed a fix to develop, and this will make it into the next release.  I'll also put a copy of our CI-server's pre-compiled executable here once that's done building, in case you need this functionality ASAP and can't build from source.

**Closed** 2019-04-11 03:09 UTC

**Comment by antpiron** [comment] 2019-04-24 07:48
Sorry for the inconvenience. I completely missed this point. My test set was too small and none were doubles. I was in the process of writting a bug fix...

Anyway, thanks for the correction.
