### ISSUE TITLE
Gibbs and Bootstrap issues

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/salmon#58] opened 2016-05-11 20:52 UTC
Hi, I was trying to investigate a thing using the Gibbs samples (and bootstraps).

I vaguely recall seeing both issues I'm reporting here somewhere, but I can't find those by searching.

I used Salmon 0.6.0, first with this command

    salmon quant \
    -i /nfs/research2/teichmann/reference/danio-rerio/salmon/zv9_cdna_ercc_gfp_index \
    -l IU \
    -p 4 \
    -1 SRS515267_1.fastq \
    -2 SRS515267_2.fastq \
    -o /tmp/SRS515267_salmon_out \
    --biasCorrect \
    --useFSPD \
    --numGibbsSamples 100 \
    && mv /tmp/SRS515267_salmon_out ."

Then I converted the Gibbs samples bootstrap files to a TSV with the script in this repository.

The problem is that I get rather nonsensical values in the Gibbs samples (attaching a screenshot of my notebook because that is the quickest way...)

![image](https://cloud.githubusercontent.com/assets/668803/15195757/2ccadcd4-17c1-11e6-8457-d8540cd59471.png)

What I vaguely recall is that the Gibbs samples does not work with one of the bias modelling options?

I think there should at least be a warning in the documentation entry for `--numGibbsSamples`

After this I ran the same command, but replaced `--numGibbsSamples` with `--numBootstraps`.

Now I get this:

![image](https://cloud.githubusercontent.com/assets/668803/15195925/f81cd64e-17c1-11e6-9c5b-d7a29e2e5bc9.png)

The values seem all right, except I'd prefer the values to be TPM's rather than counts. Is the transformation I'm doing in "line 78" fine for converting the counts back to TPM? Or is it more complicated than that?

**Comment by rob-p** [comment] 2016-05-11 21:02
Hi Valentine,

  Thanks for reporting this!  Do you have any recollection of what option might be incompatible with Gibbs?  Specifically, it's interesting that it doesn't work with Gibbs (it looks like you're getting `std::numeric_limits<double>::min()` everywhere) but works with Bootstrapping.  I will certainly look into this and will document (and make an explicit warning) any known incompatibilities in the next release.  I'd very much like to fix the issue with Gibbs sampling, as it's substantially faster than bootstrapping for a large number of samples.  Actually, there's a fairly substantial upgrade to the bias modeling that is just about ready and will be part of the next release (which is, in fact, what has delayed v0.7.0 for so long).

  Regarding converting counts back to TPM, what you're doing there looks like it's actually converting to NPM (nucleotides per million) which is a relative abundance measure that is not normalized for transcript length.  To get TPM estimates from the bootstrap numbers what you would want to do would be something like:  `TPM = 1e6 * ((bootstraps / effective_lengths) / (bootstraps / effective_lengths).sum())`.

--Rob

**Comment by vals** [comment] 2016-05-12 20:00
Hi Rob,

I've been trying various combinations of options to get the Gibbs sampling working, but it doesn't work for any of the combinations I tried. The normal quantification output is fine.

I also tried Sailfish, and with that the Gibbs sampling doesn't work either. (Same `4.243992e-314` style values).

Thanks for clarifying about the counts in the output. Generally I'm a bit confused about why one wouldn't have the counts just be "corrected" for length, but maybe I'll make a separate issue about that at another point..

**Comment by rob-p** [comment] 2016-05-12 20:38
Hi Valentine,

  That's not good!  I suppose that testing the gibbs sampling should be added to our standard set of regression tests.  Can you provide me with a data set that reproduces this issue?  I'll track it down and figure out why Gibbs is behaving badly.

--Rob

**Comment by vals** [comment] 2016-05-12 20:45
I've been using the SRA dataset `SRS515267` for this. To quickly try different combinations of parameters I just looked at the first 1 million reads of that (pretty deep) data.

Until I do some cleaning in my directories a few months from now, you can find fastq files and the transcriptome I use here: http://www.ebi.ac.uk/~vale/failing-gibbs/

**Comment by rob-p** [comment] 2016-05-14 01:00
Hi Valentine,

  I'm unable to reproduce this issue, and I wonder if the problem is in the parsing of the Gibbs samples.  Granted, the existing format is horribly documented, so I'm working on fixing this now.  However, one important difference is that while both the bootstrap samples and Gibbs samples are stored in a binary, gzipped file, the bootstrap samples are double-precision floating point values, while the bootstrap samples are 32-bit signed integers.  Thus, if you use the same code to read both, you will end up mis-interpreting the Gibbs samples.  In python, reading the samples would be something like:

```
v = struct.unpack_from(''.join(['<i']*num_txp), gzip.open('sample_file.gz').read())
```

When I do this, I get reasonable-looking integral counts in v.

--Rob

**Comment by rob-p** [comment] 2016-05-14 19:44
This is fixed (@vals, can you confirm?) by Valentine's pull request, so I'm closing this issue.

**Closed by rob-p** 2016-05-14 19:44 UTC

**Comment by vals** [comment] 2016-05-15 00:11
Yep problem was due to parsing!
