### ISSUE TITLE
Unexpected counts for partially-nested features in alignment mode

### ISSUE THREAD

**Issue by gnaisha** [COMBINE-lab/salmon#605] opened 2020-12-22 14:58 UTC
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon

**Describe the bug**
The alignments to two partially overlapping transcripts suggest that only one of the transcripts is expressed, but salmon is assigning the majority of these reads to the other transcript. Even ignoring coverage differences that suggest that transcript ENST00000364953.1 is the source of these reads, this transcript is the only one of the two with unambiguous alignments, and so I would expect salmon to count the rest of the reads for this transcript. I tried quantifying this same bam with eXpress, and it produces the expected result of counting all the reads for transcript ENST00000364953.1.

The alignments were generated with STAR, aligning to the GRCh38 genome and using STAR's transcriptome bam output (using gencode v35 main annotations). I'm happy to provide the small bam containing these alignments in transcriptome space, but I don't seem to be able to upload this here.

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used? 1.4.0
  * How was salmon installed (compiled, downloaded executable, through bioconda)? bioconda
  * Which reference (e.g. transcriptome) was used? GRCh38/gencode v35
  * Which read files were used?
  * Which which program options were used? -l 'U'

**Expected behavior**
salmon counting all the reads for transcript ENST00000364953.1

**Screenshots**
<img width="998" alt="salmon_unexpected_counts" src="https://user-images.githubusercontent.com/17803131/102898647-cf7e8f00-4437-11eb-90bb-37b8498ba333.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 
Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Additional context**

**Comment by rob-p** [comment] 2020-12-22 15:24
Hi @gnaisha,

  Thank you for the detailed error report.  Would it be possible to provide the BAM file that generated this behavior, or the commands used to generate this BAM file?  That way we can try to reproduce and diagnose the issue.

**Comment by gnaisha** [comment] 2020-12-22 15:41
Hi @rob-p,

Here's the file. Thanks for taking a look at this!

[sample_nested_transcripts_ENST00000364953-1_ENST00000375633-5.bam.zip](https://github.com/COMBINE-lab/salmon/files/5730751/sample_nested_transcripts_ENST00000364953-1_ENST00000375633-5.bam.zip)

**Comment by rob-p** [comment] 2020-12-22 19:40
Hi @gnaisha,

  Thank you for providing the file to reproduce the issue.  So, the difference here is all in the default fragment length mean and standard deviation that salmon and eXpress use.  This really only matters in single-end libraries like this, since in paired-end libraries both tools will estimate the fragment length distribution from the data itself.  Nonetheless, if not given specific parameters to override the default, salmon assumes μ = 250 and σ = 25, while eXpress assumes μ = 200 and σ = 80.  If you run salmon like:

```
salmon quant -lU -t transcriptome.fa -a sample_nested_transcripts_ENST00000364953-1_ENST00000375633-5.bam --fldMean 200 --fldSD 80 -o quant_directory
```

Then you will see the following behavior for these transcripts:

```
ENST00000364953.1       64      23.127  1000000.000000  49.000
ENST00000375633.5       586     384.567 0.000000        0.000
```

So that the all of the reads are, indeed, allocated to the former.  The effect of the transcript length on the assignment probabilities is a direct result of the probabilistic model (and due to the length effect that actually exists in the full-length RNA-seq assay).  It's unfortunate that there's not a good way to estimate the fragment length distribution in single-end data, and so we are left with having to set some defaults.  Depending on the actual library, different defaults will match better or worse.  On the plus side, it's easy to change these values if you have better knowledge of the parameters or reason to believe that one value will work better than another.

**Comment by rob-p** [comment] 2020-12-23 20:18
Hi @gnaisha,

  Since I believe this resolves this particular issue, I'm going to close it.  However, feel free to comment back here if you have further questions.

Best,
Rob

**Closed by rob-p** 2020-12-23 20:18 UTC

**Comment by gnaisha** [comment] 2020-12-29 12:50
Hi Rob,

Thanks for the clarity regarding the effect of insert size distribution on quantification. That does resolve this issue, and gives me a path going forward using Salmon for this data.

However, I am trying to use Salmon for small RNA-Seq data, where the insert size is equal to read length for most reads after adapter trimming. Would it be possible to add a flag to use read length as a proxy for insert size, potentially with a fallback to fldMean/fldSD in the case of full-length, untrimmed reads? This is something I would be willing to contribute myself, if it sounds appropriate.

Thanks,
Gautam
