### ISSUE TITLE
error when indexing transcroptome

### ISSUE THREAD

**Issue by bzmby** [COMBINE-lab/salmon#730] opened 2021-12-22 11:17 UTC
I have made a singularity container for the salmon v1.6.0 and I am working with centOS. 
I am trying to make an index file for human transcript using this command:

**salmon index -t hg19_EnsenmblGenes_sequence_ensenmbl.fasta -i Ensembl_hg19_salmon_index**

But I am getting this error:

**Version Info: This is the most recent version of salmon.
exception : [the option '--index' is required but missing]. Exiting.**
 
Then I tried this command:

**salmon  --index -t hg19_EnsenmblGenes_sequence_ensenmbl.fasta -i Ensembl_hg19_salmon_index**

Then I got this error:

**Version Info: This is the most recent version of salmon.
salmon was invoked improperly.
For usage information, try salmon --help
Exiting.**

Do you know how I can fix the issue?

**Comment by rob-p** [comment] 2021-12-31 17:41
I think this issue was raised on Biostar; is that the case? If not, there was a very similar issue, and the command line:

```
salmon index -t hg19_EnsenmblGenes_sequence_ensenmbl.fasta --index Ensembl_hg19_salmon_index
```

seemed to work.  By the way, the original command looks fine, and I don't have any idea why it wouldn't work as posted.  Unfortunately, I've not been able to reproduce the issue locally.

**Comment by rob-p** [comment] 2022-01-11 23:06
Since I can't reproduce this locally? I'm going to close this until more information is available.

**Closed by rob-p** 2022-01-11 23:06 UTC
