### ISSUE TITLE
--writeMappings not writting output to file

### ISSUE THREAD

**Issue by uros-sipetic** [COMBINE-lab/salmon#86] opened 2016-09-05 13:03 UTC
Hey, I tried the new option --writeMappings, and I called it like this "--writeMappings mappings_info", in order to write the resulting information to a file instead of printing it to stdout.
But it got printed to stdout nevertheless and I never get the mappings_info file, which I specified in the argument.
Are the results still ought to be printed to stdout, in addition to being written to a file?
And does writing to a file work, or should I pipe a command to do so nevertheless? 

EDIT: Here's the complete command I used:
salmon quant -i ucsc.hg19.transcriptome_salmon_index -1 reads.pe_1.fastq -2 reads.pe_2.fastq --writeMappings mappings_info -o test_output -l A -p 2

**Comment by rob-p** [comment] 2016-09-05 15:34
Hi @uros-sipetic,

  Thanks for reporting this.  I can't reproduce the issue that, when I pass an argument to `writeMappings`, the SAM data is still written to stdout.  Could you tell me if you're using the pre-compiled binary, and if so, what type of system you're running on?   However, I can produce a different issue which may be related (and might be an issue with the logic for checking if a directory exists).  Can you try the following command in your case and tell me what happens?

`salmon quant -i ucsc.hg19.transcriptome_salmon_index -1 reads.pe_1.fastq -2 reads.pe_2.fastq --writeMappings test_output/mappings_info -o test_output -l A -p 2`

**Comment by uros-sipetic** [comment] 2016-09-05 16:15
Hi
I did use the pre-compiled binaries and the system I use is ubuntu 14.04.
Hmm.. even with the change you wrote, I seem to be getting similar results.
Does the order of parameters matter? I.e. in my command line, should I put -o first and then --writeMappings?

**Comment by rob-p** [comment] 2016-09-05 18:37
The order of the argument's shouldn't matter here.  If I switch around `-o` and `--writeMappings` I still don't get output to stdout.  Could you paste the contents of `cmd_info.json` in the quantification directory, and also the result of `uname -a`?  Our main dev box is also Ubuntu 14.04, so I wouldn't think that the OS version should be an issue given that I can't repro this behavior.

**Comment by uros-sipetic** [comment] 2016-09-05 20:29
I'll double check these days if I did something wrong, to see why I'm not getting the output file. In the meantime, here's the cmd_info.json:

{
    "salmon_version": "0.7.2",
    "index": "ucsc.hg19.transcriptome_salmon_index",
    "libType": "A",
    "mates1": "reads.pe_1.fastq",
    "mates2": "reads.pe_2.fastq",
    "output": "reads.pe_salmon_quant",
    "threads": "2",
    "auxDir": "aux_info",
    "writeMappings": [],
    "": "./reads.pe.salmon_quant_mapping_info.sam",
    "auxDir": "aux_info"
}

**Comment by rob-p** [comment] 2016-09-05 20:33
Ahh!  Well, for some reason it appears that your command line is being parsed incorrectly.  This file, `cmd_info.json` is a JSON dictionary representing the arguments passed to the program (and some other info).  Here you can see that the `writeMappings` key has an empty value `[]`.  Further, you can see that there is then an *empty* key `""` that has the value that you intended to assign to `writeMappings` (i.e. `./reads.pe.salmon_quant_mapping_info.sam`).  This explains why you're seeing the behavior you are (because when the program interprets `writeMappings` as having been set without an explicit argument, it writes to stdout).  However, now the mystery is why the program options are being interpreted in this way.  To give you an example of the difference, here is how my `cmd_info.json` looks:

```
{
    "salmon_version": "0.7.3",
    "index": "sample_data/sample_salmon_quasi_index",
    "libType": "A",
    "mates1": "sample_data/reads_1.fastq",
    "mates2": "sample_data/reads_2.fastq",
    "threads": "8",
    "writeMappings": "map.sam",
    "output": "write_quant_mappings",
    "auxDir": "aux_info"
}
```

Note how the `writeMappings` key has a value and how there is no `""` key.

**Comment by rob-p** [comment] 2016-09-05 20:48
No problem!  Once you can confirm that this is the issue (and that fixes to your script resolve the problem), just let me know and I'll close the issue.

**Comment by uros-sipetic** [comment] 2016-09-06 09:52
Hi @rob-p 
So I tried testing again, running Salmon without any scripts, and again I keep having the same issue. The command line part with the parameter in question is (copy-pasted): 
 "--writeMappings test_output/mappings_info" 
and the cmd_info.json file looks the same as before, with the "" key. 
Do I need to call that parameter differently, like --writeMappings=file_name, or...? 
If I did made some stupid mistake, sorry then upfront for wasting your time, in the meantime I'll try and test this a couple of more times in the next few days and try and see what's up.

**Comment by rob-p** [comment] 2016-09-06 12:32
Ok, I was able to reproduce your issue.  Interestingly, it happens for me *only* with the pre-compiled binary.  My guess is that it's a problem with using both default and implicit options with the older version of boost with which the pre-compiled binary was made (I make the binary under a docker image with an old version of CentOS to maximize compatibility).  A temporary work-around is to use the form `--writeMapping=test_output/mappings_info`, which seems to solve the issue that was occurring.  I'll make a note of this on the release page and see if I can find a way around this when building the next binary release.

**Comment by uros-sipetic** [comment] 2016-09-06 12:52
Hey this totally worked actually. Thanks for your answers Rob! Glad it got resolved!

**Comment by rob-p** [comment] 2016-09-06 13:00
Likewise!  Sorry for the trouble.  Holy Build Box (the environment I use to make the pre-compiled binaries) is great.  But it looks like I have to figure out which component (boost libraries, gcc version, etc.) is causing this behavior there.

**Comment by rob-p** [comment] 2016-09-06 15:11
Hi @uros-sipetic,

  Actually, it looks like what you're seeing is [actually the intended behavior](http://stackoverflow.com/questions/39351580/default-and-implicit-arguments-in-boost-program-options), and the behavior where `--writeMappings ./test_output` works is actually unexpected.  Thus, I don't anticipate this being "fixed" in a future release, since it's actually behaving as expected.  So, you can use either `--writeMappings=<outfile>` or `--writeMappings<outfile>` to get the correct behavior.  I might look into why my system accepts `--writeMappings <outfile>`, but probably won't dig too deep since I expect the behavior is probably ill defined.

**Closed by rob-p** 2016-09-06 15:11 UTC
