### ISSUE TITLE
Segmentation fault on some data when using `--useFSPD`

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/salmon#64] opened 2016-06-21 09:14 UTC
I've been running Salmon on some data from accession SRP034543. For some it works fine, but some there is segmentation fault when using the `--useFSPD`. For an example run where it fails, have a look at accession SRR2048254.

Here is the command I ran along with output

```
$ salmon quant \
> -i /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna_38.p4.83_repbase20.11_ercc_SIRV.fa \
> -l IU \
> -1 <(zcat /nfs/research2/teichmann/valentine/data/SRP034543/SRR2048254_1.fastq.gz) \
> -2 <(zcat /nfs/research2/teichmann/valentine/data/SRP034543/SRR2048254_2.fastq.gz) \
> -o /tmp/SRR2048254_salmon_out \
> --biasCorrect \
> --useFSPD
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon
# [ command ] => quant
# [ index ] => { /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna_38.p4.83_repbase20.11_ercc_SIRV.fa }
# [ libType ] => { IU }
# [ mates1 ] => { /dev/fd/63 }
# [ mates2 ] => { /dev/fd/62 }
# [ output ] => { /tmp/SRR2048254_salmon_out }
# [ biasCorrect ] => { }
# [ useFSPD ] => { }
Logs will be written to /tmp/SRR2048254_salmon_out/logs
[2016-06-21 10:04:29.524] [jointLog] [info] parsing read library format
there is 1 lib
Loading 32-bit quasi indextcmalloc: large alloc 4294967296 bytes == 0x4d084000 @
[2016-06-21 10:04:30.159] [stderrLog] [info] Loading Suffix Array
[2016-06-21 10:04:30.159] [stderrLog] [info] Loading Position Hash
[2016-06-21 10:04:30.158] [jointLog] [info] Loading Quasi index
[2016-06-21 10:04:32.681] [stderrLog] [info] Loading Transcript Info
[2016-06-21 10:04:33.686] [stderrLog] [info] Loading Rank-Select Bit Array
[2016-06-21 10:04:34.050] [stderrLog] [info] There were 115426 set bits in the bit array
[2016-06-21 10:04:34.376] [stderrLog] [info] Computing transcript lengths
[2016-06-21 10:04:34.377] [stderrLog] [info] Waiting to finish loading hash
Index contained 115426 targets
[2016-06-21 10:04:47.033] [jointLog] [info] done
[2016-06-21 10:04:47.033] [stderrLog] [info] Done loading index



processed 6500000 fragments
hits: 13927069, hits per frag:  2.15389







[2016-06-21 10:05:13.847] [jointLog] [info] Computed 165969 rich equivalence classes for further processing
[2016-06-21 10:05:13.847] [jointLog] [info] Counted 6514601 total reads in the equivalence classes
[2016-06-21 10:05:13.893] [jointLog] [info] Mapping rate = 95.0922%

[2016-06-21 10:05:13.893] [jointLog] [info] finished quantifyLibrary()
[2016-06-21 10:05:13.894] [jointLog] [info] Starting optimizer
Segmentation fault (core dumped)
```

It runs fine when disabling `--useFSPD`

**Comment by rob-p** [comment] 2016-06-21 12:30
Hi Valentine,

  Thanks for all of the detailed info to reproduce this; I'll try and take a look at it soon.  Since there is *a lot* of work going on in the develop branch (and good stuff coming in v0.7.0), it actually looks like `--useFSPD` will be replaced with a `--posBias` flag that models both 5' and 3' position specific bias.  Of course, we're still working on / testing that feature.  In the mean time, I'll see if I can find what's causing this problem.

--Rob

**Comment by rob-p** [comment] 2016-08-21 01:59
Hi @vals,

  So there was a very subtle bug in `useFSPD` that would (in a very non-reproducible manner) trigger such a segfault.  It was related to some very tricky locking behavior.  However, the manner in which `useFSPD` corrected for position specific bias isn't actually compatible with our new sequence-specific and fragment-gc bias models.  Thus, I've deprecated `useFSPD`.  The replacement is the flag `posBias`.  This models the same type of positional bias, but does so in a way that is compatible with our other bias models.  It also doesn't rely on the tricky threading behavior, so it should be more stable.  Unlike sequence-specific and fragment-gc bias, however, the `posBias` option is still *experimental* in the 0.7.0 release.  However, we have been testing it internally, and I'd be very grateful for your feedback if you have a chance to try it out.  Assuming things look good, we can promote it from experimental in the next release.

**Comment by rob-p** [comment] 2017-03-09 22:55
Since `--useFSPD` is now deprecated, and this behavior should not occur with the new positional bias models.  I'm going to go ahead and close this.

**Closed by rob-p** 2017-03-09 22:55 UTC
