### ISSUE TITLE
Cannot get index, decoy issue

### ISSUE THREAD

**Issue by gambardella** [COMBINE-lab/salmon#572] opened 2020-10-14 17:25 UTC
Hello,
I come back to Salmon after a few months, and meet an issue I did not before. First of all, I upgraded from version 1.2 to 1.3
Salmon refuse to index, and I am not quite sure why. I followed the "selective alignment tutorial", which worked before (although with different genomes). Here are the commands (I checked the md5sum of both assembly and transcripts and they are fine)

grep "^>" <(gunzip -c ../../../Genomes/GRCm38.primary_assembly.genome.fa.gz) | cut -d " " -f 1 > decoys.txt
sed -i.bak -e 's/>//g' decoys.txt
cat ../../../Genomes/gencode.v35.transcripts.fa.gz ../../../Genomes/GRCh38.primary_assembly.genome.fa.gz > gentrome.fa.gz
salmon index -t gentrome.fa.gz -d decoys.txt -p 4 -i salmon_index --gencode

All I get is a long list of warning:

Version Info: This is the most recent version of salmon.
[2020-10-14 18:04:19.244] [jLog] [info] building index
out : salmon_index
[2020-10-14 18:04:19.244] [puff::index::jointLog] [info] Running fixFasta

[Step 1 of 4] : counting k-mers
[2020-10-14 18:04:21.116] [puff::index::jointLog] [warning] Entry with header [ENST00000473810.1|ENSG00000239255.1|OTTHUMG00000157482.1|OTTHUMT00000348942.1|AC007620.1-201|AC007620.1|25|processed_pseudogene|], had length less than equal to the k-mer length of 31 (perhaps after poly-A clipping)                                                                                                                                
[2020-10-14 18:04:21.247] [puff::index::jointLog] [warning] Entry with header [ENST00000603775.1|ENSG00000271544.1|OTTHUMG00000184300.1|OTTHUMT00000468575.1|AC006499.8-201|AC006499.8|23|processed_pseudogene|], had length less than equal to the k-mer length of 31 (perhaps after poly-A clipping)     

and also (this is normal for long ncRNA I guess)

[2020-10-14 18:19:30.936] [puff::index::jointLog] [warning] Entry with header [ENST00000674361.1|ENSG00000241743.4|OTTHUMG00000022220.5|OTTHUMT00000530527.1|XACT-203|XACT|347561|lncRNA|] was longer than 200000 nucleotides.  This is probably a chromosome instead of a transcript.

And then it all breaks

[2020-10-14 18:20:34.751] [puff::index::jointLog] [critical] Observed a non-decoy sequence [chr20] after having already observed a decoy. However, it is required that any decoy target records appear, consecutively, at the end of the input fasta file.  Please re-format your input file so that all decoy records appear contiguously at the end of the file, after all valid (non-decoy) records

I get nothing.

What do I do wrong?

**Comment by rob-p** [comment] 2020-10-14 17:31
Hi @gambardella,

  Thank you for the detailed issue report.  The warnings are noisy, but not themselves problematic (there's a reasonable discussion to be had if we should make the process less noisy by default, and have the user ask for verbosity to get all of the warnings etc.).  However, the last line is an error, and this is the cause of the problem.  It seems to suggest that `chr20`, which appeared in the `gentrome.fa.gz` file did not have its name appear in `decoys.txt`, and that it occurred after some records that _were_ marked as decoys.  I'm assuming that `chr20` _should_ appear as a decoy here.  Can you `grep` for `chr20` in the `decoys.txt` file and see if it shows up?  If not, the question would be why it's not placed there by your first command.

--Rob

**Comment by gambardella** [comment] 2020-10-14 17:39
Hi Rob,

I made such a stupid mistake, it is embarrassing to write it down, and I am ashamed of having wasted your time. Last time I used Salmon was to process a murine Chromium dataset... Copy/paste fossil ... :-( 
Time to call it a day.

**Comment by rob-p** [comment] 2020-10-14 17:41
No worries, Nicolas!  I'm glad that you were able to figure out what went wrong.  I'm sure coming back to it with fresh eyes will help make the rest of the analysis easier too :).

**Closed by rob-p** 2020-10-14 17:41 UTC
