### ISSUE TITLE
Feature request: RefSeq datasets

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [COMBINE-lab/salmon#373] opened 2019-06-12 13:49 UTC
Hi,

Sorry if this has been covered before, but is it possible to build a RefSeq based transcriptome and decoys. If this is not something you plan on doing, can you share the build requirements so I can build my own datasets please?

thanks

**Comment by k3yavi** [comment] 2019-06-12 13:54
Hi @PeteCausey-Freeman ,

You can access the script and the requirements [here](https://github.com/COMBINE-lab/SalmonTools). Look for `generateDecoyTranscriptome`.

**Comment by PeteCausey-Freeman** [comment] 2019-06-12 15:16
Brilliant. Thanks.

**Comment by k3yavi** [comment] 2019-11-03 14:22
I think the issue is resolved here, closing it but feel free to reopen.

**Closed by k3yavi** 2019-11-03 14:22 UTC
Labels: SA
