### ISSUE TITLE
Build failure (libtbb)

### ISSUE THREAD

**Issue by jorvis** [COMBINE-lab/salmon#51] opened 2016-03-25 05:20 UTC
My first attempt at building salmon failed during what appears to be the tbblib build step.  I'm going to continue by building tbb on my own and starting over, but wanted to post notes here.  Steps:

```
$ uname -a
Linux jorvisvm-lx 2.6.18-371.1.2.el5 #1 SMP Mon Oct 7 16:34:35 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux

$ pwd
/tmp/salmon-0.6.1-pre

$ mkdir build && cd build

## set up environment:
export PATH=/usr/local/packages/gcc-5.3.0/bin:$PATH

$ cmake -DFETCH_BOOST=TRUE -DCMAKE_INSTALL_PREFIX=/usr/local/packages/salmon-v0.6.1-pre ../
$ make
```

[build.failure.txt](https://github.com/COMBINE-lab/salmon/files/189095/build.failure.txt)

**Comment by jorvis** [comment] 2016-03-25 06:08
Building my own TBB hasn't helped.  I installed it and set its path on the command line using -DTBB_INSTALL_DIR=/usr/local/packages/intel-tbb.4.4.3.181 and still CMAKE returns this in its output:

```
ERROR: Intel TBB NOT found!
-- Looked for Threading Building Blocks in /usr/local/packages/intel-tbb.4.4.3.181/compilers_and_libraries_2016
Build system will fetch and build Intel Threading Building Blocks
```

I've tried numerous subdirectories as well but can't seem to find what it's looking for to determine the TPP directory.  Setting TBB_INSTALL_DIR also changed nothing.

Currently stuck on my salmon build.

**Comment by rob-p** [comment] 2016-03-25 12:06
Hrmm the first error looks like some missing symbols; strange, since it seems to be looking in the right place.  Can you tell me what system / compiler etc. are being used?

**Comment by jorvis** [comment] 2016-03-25 13:45
This is RHEL5, and I'm using gcc-5.3.0

**Comment by rob-p** [comment] 2016-03-25 14:17
Hi @jorvis,

  @sjackman ran into a [similar (but different) issue](https://github.com/COMBINE-lab/salmon/issues/46#issuecomment-193963209), and the root cause seems to be GCC5.3.  My best guess is that there is some symbol munging that is incompatible between things compiled with GCC 4.x and GCC 5.x.  The newest version of GCC seems to break quite a bit of software.  I haven't installed it and tried to build with it yet, but I'll add it to my list of things to investigate.  For the time being, would it be possible to build with GCC 4.X (where X > = 8.2), or to use the [pre-compiled binary](https://github.com/COMBINE-lab/salmon/releases/download/v0.6.0/SalmonBeta-0.6.0_DebianSqueeze.tar.gz)?

**Comment by jorvis** [comment] 2016-03-25 15:23
I just tried with gcc 4.9.0 and errored out at the the same point (attached).  I'll try using the pre-compiled ones. 

[compile.error.txt](https://github.com/COMBINE-lab/salmon/files/189653/compile.error.txt)

**Comment by rob-p** [comment] 2016-03-25 15:24
Thanks for testing that out.  In this case, I'll try an dig more deeply into why you're having issues compiling from source.  In the mean time, I hope the pre-compiled binary will work for you.

**Comment by jorvis** [comment] 2016-03-30 20:31
I was able to successfully get an index built using precompiled binaries.  Not sure if you want to keep this open, but I'll be happy to help out running commands however you need.

**Comment by rob-p** [comment] 2017-03-09 22:57
Since I can't reproduce this in an environment I have access to, I'm going to close this for now.  However, if it's still an issue that needs to be resolved, please feel free to comment and I'll re-open.

**Closed by rob-p** 2017-03-09 22:57 UTC
