### ISSUE TITLE
question about Alevin tool

### ISSUE THREAD

**Issue by Vivianstats** [COMBINE-lab/salmon#574] opened 2020-10-17 03:01 UTC
I am very interested in using your Alevin tool to process my 10x scRNA-seq data. I wonder if there's a deduplication option in Alevin that can output deduplexed bam files, as UMI-tools dedup does? I need the exact positions of mapped reads in addition to read counts for my analysis.

**Comment by k3yavi** [comment] 2020-10-17 03:29
Hi @Vivianstats ,

Thanks for reaching out. You can certainly dump the CB and UMI tagged Bam file, however, the problem is we can't mark a subset of reads as deduplicated. Alevin's algorithm does not deduplicate UMI at the read level instead we deduplicate at the level of an arboreacence. Basically, the problems is it's not clear which alignment / read should be marked as primary because of following reasons:

1.) Alevin does fractional assignment of ambiguous reads.
2.) If there are multiple equally good alignment of a read which alignment should be marked primary for the deduplication ? 
3.) Even in the UMI tools world, a UMI from a single gene can come from a range of genomic loci, because of the random process of sequence fragmentation. I am not quite sure what UMI tools does, I can check with the developers, but I feel randomly marking one among multiple equally good choice is not right.

Hope it helps.

@rob-p  feel free to add if I missed something.

**Comment by Vivianstats** [comment] 2020-10-20 19:19
Hi,
Thank you vey much for explaining the reasons in detail. So, the main challenge in deduplication at the read level is that some reads are aligned to multiple positions, right?

I also have a question regrading the third point. My understanding is that reads that map to the same genomic location and have the same UMI and CB will be treated as PCR duplicates, and only one of such reads will be retained in the deduplication process. Can you elaborate on why "a UMI from a single gene can come from a range of genomic loci"? Do 3' scRNA-seq protocols also involve CDNA fragmentation?

**Comment by k3yavi** [comment] 2020-10-21 02:09
yep, at least in my understanding, the 3' single cell 10x protocol goes through the process of cDNA fragmentation post amplification. I think you can more information from [here](https://assets.ctfassets.net/an68im79xiti/4tjk4KvXzTWgTs8f3tvUjq/2259891d68c53693e753e1b45e42de2d/CG000183_ChromiumSingleCell3__v3_UG_Rev_C.pdf)

**Comment by k3yavi** [comment] 2020-12-03 17:22
Closing this due to inactivity, please feel free to reopen.

**Closed by k3yavi** 2020-12-03 17:22 UTC
Labels: alevin
