### ISSUE TITLE
Possible out of bounds access when alignment softclip co-incides with transcript boundary

### ISSUE THREAD

**Issue by francicco** [COMBINE-lab/salmon#231] opened 2018-06-03 09:35 UTC
Hi,

I'm trying to compile Salmon like this:
`cmake -DTBB_INSTALL_DIR=/home/fc464/software/tbb -DFETCH_BOOST=TRUE -DCMAKE_INSTALL_PREFIX=/home/fc464/software/salmon ..`

but during
`make`

I get this error:

```
[ 50%] Built target alevin_core
[ 55%] Built target ksw2pp_basic
[ 57%] Built target ksw2pp_sse2
[ 58%] Built target ksw2pp
[ 72%] Built target salmon_core
[ 73%] Linking CXX executable unitTests
../../external/install/lib/libstaden-read.a(libstaden_read_la-open_trace_file.o): In function `find_file_url':
open_trace_file.c:(.text+0xd30): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /usr/local/software/spack/spack-0.11.2/opt/spack/linux-rhel7-x86_64/gcc-5.4.0/bzip2-1.0.6-xsgsccpkklxd745bl2gbgyhube56o6w4/lib/libbz2.a(bzlib.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/unitTests] Error 1
make[1]: *** [src/CMakeFiles/unitTests.dir/all] Error 2
make: *** [all] Error 2
```

What's wrong?
Best
F

**Comment by rob-p** [comment] 2018-06-03 14:08
Hi @francicco,

  It looks like the problem is that the compiler being used is newer than the linker being used to link bzip2 here (see e.g. [this](https://stackoverflow.com/questions/46058050/unable-to-compile-unrecognized-relocation)).  You should try and make sure the appropriate (newer) linker is present in your path before the older one. Another option, of course, would be to simply install salmon through Bioconda, which will take care of such issues for you.

Best,
Rob

**Comment by francicco** [comment] 2018-06-04 18:14
Ho @rob-p,

I changed gcc version so many times, I changed cluster, nothing. I tried with conda and it works, kind of. But apparently the bioconda version the [0.101](https://anaconda.org/bioconda/salmon) and is not the latest:

```
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and minor bug fixes; please upgrade at your
earliest convenience.
###
```
Anything to be worried?
Thanks
F

**Comment by francicco** [comment] 2018-06-04 18:23
acutally is the v0.8.1

**Comment by rob-p** [comment] 2018-06-04 18:29
Hi @francicco ,

  Can you try the following?

```
$ conda config --add channels conda-forge
$ conda config --add channels bioconda
$ conda create -n salmon salmon=0.10.1
```

**Comment by francicco** [comment] 2018-06-04 18:52
works!!!! 

`salmon 0.10.1`

Thank you so much!!!
F

**Comment by rob-p** [comment] 2018-06-04 18:54
My pleasure!  Thanks for working through the issues :).

**Comment by francicco** [comment] 2018-06-04 18:58
actually...

`processed 3000000 reads in current round/home/lv70640/c7701100/Projects/ZebraFish/ZebFish.Transcriptome.sh: line 104: 19000 Segmentation fault`

It was better before
F

**Comment by francicco** [comment] 2018-06-04 19:02
`source deactivate`

`salmon (alignment-based) v0.8.1` and it works!

**Comment by rob-p** [comment] 2018-06-04 19:05
Interesting!  I see you're running in alignment-based mode.  Is it possible to share the data causing the segfault?  I'd like to try and debug it if possible.

**Comment by francicco** [comment] 2018-06-04 19:06
No problem, the bam is large. How do I send it?
F

**Comment by rob-p** [comment] 2018-06-04 19:16
How large is "large"?  I propose to share a GoogleDrive folder with you.  Can you send me an e-mail to which I can share a google drive link?

**Comment by francicco** [comment] 2018-06-04 20:27
fc464@cam.ac.uk

**Comment by rob-p** [comment] 2018-06-05 15:58
Hi @francicco ,

  Thanks for sharing the data.  I'm able to re-create the problem and am trying to debug it now.  The reason you see this behavior in 0.10.1 but not in 0.8.1 is because in 0.10.1 the error model is enabled by default, while it is not in 0.8.1.  If you run the newest salmon with `--noErrorModel` (the default in 0.8.1), your sample runs to completion.  However, using the error model helps (which is why I made it the default), so I'm trying to debug what's happening there.  I'll keep you posted.

  One more point worth mentioning.  I noticed you are passing a coordinate sorted BAM file.  For quantification with salmon, you really should not be passing a coordinate sorted BAM.  This is because Salmon expects the alignments to appear in a random order, which is important for how the streaming stochastic variational algorithm learns the auxiliary parameters.  Sorting by coordinates biases the models towards the isoforms that appear earliest in the BAM file.

**Comment by rob-p** [comment] 2018-06-05 19:29
More to report --- it also looks like your FASTA file has duplicates.  Specifically, if you look at just the actual sequence name (i.e. breaking the header after the first space), there are ~100 duplicates.  This will definitely cause some issues.  I'm not sure if fixing this would resolve all of the problems, but if you have different sequences, the actual sequence name should be different in the header.  For example --- there are 2 sequences named `danRer10_ncbiRefSeq_NM_201038.1`.  One has length 677 the other has length 830.  

```
>danRer10_ncbiRefSeq_NM_201038.1 range=chr1:58438370-58450110 5'pad=0 3'pad=0 strand=+ repeatMasking=none
>danRer10_ncbiRefSeq_NM_201038.1 range=chrUn_KN149781v1:4916-8644 5'pad=0 3'pad=0 strand=+ repeatMasking=none
``` 

Both appear in the SAM header (with the same name):

```
@SQ     SN:danRer10_ncbiRefSeq_NM_201038.1      LN:677
@SQ     SN:danRer10_ncbiRefSeq_NM_201038.1      LN:830
```

This will definitely confuse salmon as the transcript names must be unique.  This can result in storing a sequence in a transcript that is the wrong length, and then having the alignments refer to non-existent bases (which can lead to a segfault).  Can we fix up these issues and see if it helps resolve the problem?

**Comment by rob-p** [comment] 2018-06-05 21:02
Hi @francicco ,

  I've dug further, and in addition to these problems with the input file, there was also a specific bug in salmon's processing of the alignments for the error model.  Specifically, it was triggered when an alignment ended with a soft-clip of the reference.  I have now fixed this issue in the develop branch, and, after some more testing, will push it to a new release.

**Comment by rob-p** [comment] 2018-06-06 01:41
I'm attaching the linux binary with the fix [here](https://github.com/COMBINE-lab/salmon/files/2074498/salmon-latest_linux_x86_64.tar.gz).  Can you see if this runs without error for you (after addressing the issues with the duplicate sequences and alignment sort order mentioned above)?  If so, I'll cut it as a new release.  Thanks!

**Comment by rob-p** [comment] 2018-06-08 15:05
Since 0.10.2 is now out (and salmon is updated in bioconda), I'm going to close this issue.

**Closed by rob-p** 2018-06-08 15:05 UTC
Labels: bug, fixed in develop
