### ISSUE TITLE
NaNs generated for up to 60% of transcripts with --useFSPD and --biasCorrect turned on

### ISSUE THREAD

**Issue by warrenmcg** [COMBINE-lab/salmon#50] opened 2016-03-17 13:47 UTC
After generating issue #48, I took the recommendation of switching to the standard EM algorithm, but I'm having further problems. However, I don't think the problem was with the Variational EM algorithm, but an issue with how the dataset is behaving. 

This is with the same dataset as before (single end, rRNA-depleted, second-strand protocol, extreme depth of 170M+ reads). I have the options --useFSPD and --biasCorrect turned on with library type "SF"; the full call is 

```
salmon quant -i $SALMON_DIR -l SF -r <(gzip -c -d $IN_FILE) -o $OUTPUT \
                --numBootstraps 100 --useFSPD --geneMap $GENES \
                --biasCorrect -p 59
```

I had attempted to use wasabi and run sleuth, but I got an error where the number of transcripts passing the initial filter was "NA". I then discovered that for four samples, many of the transcripts had "-nan" generated for the "NumReads" column, and this led to all of them having "-nan" for the TPM column. One sample had ~100 that failed, but the other three had a variable 106K-109K out of 176K total transcripts fail. No warning or error was thrown during the quantifying or EM optimization steps, so I don't know what happened.

Interesting, I should note that the NaNs are only generated when both biasCorrect and useFSPD are turned on. NaNs are not generated when I use only one or neither option. (this was only tested with one sample though)

If you have immediate suggestions, that would be great. Otherwise, I can work on generating a test dataset.

**Comment by rob-p** [comment] 2016-03-17 14:03
Hi Warren,

  I apologize for the short response --- I'm on my way to a meeting.  I'm assuming that what was happening before was simply that the problem was diagnosed during VBEM as soon as it pops up, whereas, the NaNs are allowed to propagate during the standard EM.  If I had to guess (and this is just a guess), I would blame edge effects in the FSPD for the appearance of `NaN`s (not sure why this goes away without bias correction though!).  Also, were I to disable a feature, that (`--useFSPD`) would be the one I would choose to disable since it usually has a negligible effect.  That being said, I would be **very** grateful if you were able to produce a dataset that exhibits this issue, as I'd like to fix this ASAP.  My guess is that it's a rather small issue, but the problem is that NANs propagate quickly and without mercy!

**Comment by warrenmcg** [comment] 2016-03-17 14:14
No problem. I'll see what I can do, but I am leaving out of town this weekend for a wedding, so I may not be able to get it to you until next week. Alternatively, I could PM you the details of the dataset I'm working with (it's from GEO, but I don't feel comfortable broadcasting it to the world).

**Comment by rob-p** [comment] 2016-03-17 17:16
Feel free to PM me.  If it's a publicly available dataset (and standard transcript set), then I can also try and reproduce the issue from there.

**Comment by rob-p** [comment] 2016-03-25 14:13
Hi @warrenmcg,

  I just wanted to let you know that I'm investigating this now.  It looks like this may be fixed on the latest commits to the master branch, which should become an official release soon.

**Comment by warrenmcg** [comment] 2016-03-26 17:15
Hey @rob-p,

Thanks for your efforts in handling these issues! I'll try the analysis again with the updated commits, and I'll let you know if I have further issues.

**Comment by rob-p** [comment] 2016-03-27 14:31
Great; one thing I did notice is that the mapping rates for this data seemed surprisingly low.  I don't think that's related to the `NaN`s you were seeing, but it did catch my attention, since we don't normally see mapping rates like that.  Is there a hypothesis why this may be the case (e.g. it's not just Salmon's quasi-mapping, the mapping rate remains the same (or even becomes lower) when I use an aligner)?

**Comment by warrenmcg** [comment] 2016-03-27 19:26
I do have an explanation. The data was generated using an rRNA-depletion protocol. From what I've seen elsewhere, it turns out that the mapping rate is expected to be 30-40% because many of the reads are intronic, or otherwise map outside the known transcriptome, since you have all non-rRNA (PolyA+ and PolyA-).

Hope that helps! Happy Easter!

**Comment by rob-p** [comment] 2016-03-28 13:52
Ahh  — that makes sense, and makes me feel **much** better about the mapping rates I was seeing.  Happy belated Easter!

**Comment by rob-p** [comment] 2016-08-22 16:15
This is related to the way `--useFSPD` was implemented (see #64).  This flag has been deprecated, and a replacement (`--posBias`) has been introduced as of 0.7.0.  This should not exhibit the same behavior.  The `--posBias` flag is currently experimental, but will move out of that status in the next major release after it has been in the wild for a bit.  Please let me know if the [latest release](https://github.com/COMBINE-lab/salmon/releases/tag/v0.7.1) resolves this issue for you.

**Comment by warrenmcg** [comment] 2016-08-22 20:26
Thanks Rob! I won't be able to get to it until later this week at the earliest because of helping to finish a manuscript, but I'll let you know as soon as I get to it! Looking forward to the new release!

Best,
Warren

**Comment by rob-p** [comment] 2017-05-24 04:55
Internal testing suggests that these errors are gone, but feel free to report back here (and reopen this) if you still encounter it.

**Closed by rob-p** 2017-05-24 04:55 UTC
