### ISSUE TITLE
ERROR: Txp to Gene Map not found for transcripts.. no quant file in output dir

### ISSUE THREAD

**Issue by rbenel** [COMBINE-lab/salmon#326] opened 2018-12-03 10:31 UTC
alevin (single-cell mode)

**Describe the bug**
I receive the following ERROR: Txp to Gene Map not found for 102926 transcripts.

**To Reproduce**
/usr/local/bin/salmon alevin -lISR -1 cells_CTTGTA_L001_R1_001.fastq.gz -2 cells_CTTGTA_L001_R2_001.fastq.gz --celseq2 -i AlevinIndex/ -p 8 -o alevin_output --tgMap gencode.primary_assembly.tsv

Specifically, please provide at least the following information:

  * v0.12.0, compiled 
  * FASTA file labeled "Transcript sequences" from https://www.gencodegenes.org/human/ 
   * GTF file labeled "Comprehensive gene annotation - PRI" from https://www.gencodegenes.org/human/

**Expected behavior**
To receive the following files in the output dir
    quants_mat.gz – Compressed count matrix.
    quants_mat_cols.txt – Column Header (Gene-ids) of the matrix.
    quants_mat_rows.txt – Row Index (CB-ids) of the matrix.

[alevin.log](https://github.com/COMBINE-lab/salmon/files/2638932/alevin.log)
[salmon_quant.log](https://github.com/COMBINE-lab/salmon/files/2638934/salmon_quant.log)

The tgMap was created using `tximport` in R
```
library(tximport)
gtf <- paste0(local_path, "/gencode.v29.annotation.gtf")
txdb <- makeTxDbFromGFF(gtf)
txdf <- select(txdb, keys(txdb, "GENEID"), "TXNAME", "GENEID") 

txdf_switch <- data.frame(txdf$TXNAME, txdf$GENEID)  #in order to switch the order TXNAME and GENEID apppear

write_tsv(txdf_switch, paste0(local_path, "/gencode_annot/gencode.primary_assembly.v29.tsv"), col_names = FALSE)

```

**Comment by k3yavi** [comment] 2018-12-03 13:39
Hi @rbenel ,
Thanks for raising the issue.

Just a heads up I am not very experienced in `R` and I may be doing something wrong but can you please forward your `gencode.primary_assemblyv29.tsv` because it seems the file generate after following your R code to generate txp to gene map does not seem to be right. It looks like somehow `as.data.frame(txdf$TXNAME, txdf$GENEID)`is not doing the expected thing i.e. it's dumping only the gene names, at least in my testing.

One alternative would be to use bioawk script from [here](https://combine-lab.github.io/alevin-tutorial/2018/setting-up-resources/) or may be use `do.call(rbind, Map(data.frame, A=txdf$TXNAME, B=txdf$GENEID))` in R, I am not sure about the latter though.

**Comment by k3yavi** [comment] 2018-12-03 13:47
Thinking more about the another problem can be the salmon index i.e. since it's gencode and if not already specified, you might wanna add `--gencode` as the command line flag while creating the index. The problem is the _full_ name in the reference fasta and the GTF does not align, only a prefix from the fasta does.

Another thing I noticed in the logs you forwarded is that the number of CB detected by our knee heuristic seems to be undershooting. I might have to look into the data to tell more about it but the alternatives would be to explicitly specify the true/expected CB through a tsv file using flag `--whitelist` or you can force Alevin to use top X highly expressed CB with flag `--forceCells X`. Hope this helps.

**Comment by rbenel** [comment] 2018-12-03 13:57
Hi @k3yavi , 
You are absolutely correct, that the tsv file only had one column, I fixed it above. 

But the txdf was my backup... I tried your bioawk script, but I keep getting this error
`bioawk: illegal field $(), name "group"`

**Comment by rbenel** [comment] 2018-12-03 14:03
When creating the index I did use the `--gencode` flag. 

I can send you via dropbox some data and a short explanation of the experiment.

**Comment by k3yavi** [comment] 2018-12-03 14:09
I might have to look into the order of the UMI/CB issue too.
If it's possible to forward some data via dropbox that would be great, I can take a look over that in the evening.

**Comment by k3yavi** [comment] 2018-12-03 23:47
Hi @rbenel ,
I think the attached file should do the job. I used the same script in the tutorial and it worked fine. Is it possible that your bioawk version is old ? My bioawk seems to give the following:
```
╰─$ bioawk --version
awk version 20110810
```
[txp2gene.tsv.zip](https://github.com/COMBINE-lab/salmon/files/2641712/txp2gene.tsv.zip)

**Comment by rbenel** [comment] 2018-12-04 08:30
Hi @k3yavi, 
Using the tsv file from the R script above worked fine, thanks :) 

Re: bioawk -- seems to be the same version 
`bioawk --version
awk version 20110810
`

**Comment by k3yavi** [comment] 2018-12-06 05:19
Awesome, closing this one.

**Closed by k3yavi** 2018-12-06 05:19 UTC
Labels: alevin
