### ISSUE TITLE
Quantification matrix with adapted Celseq2 protocol

### ISSUE THREAD

**Issue by wmegchel** [COMBINE-lab/salmon#361] opened 2019-05-07 09:00 UTC
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
alevin

**Describe the bug**
We have an adapted Celseq2 protocol, where read1 (42bp) is used as the sequencing read and read2 (also 42bp) contains (5' -> 3') the barcode (8bp), UMI (8bp), 26 remaining nt's.

Alevin seems to run fine, but the quant matrix has a very low UMI count, which does not fit with the _MappedUMI.txt_ file or the reported alignment rate.
 
**To Reproduce**
First, I put the UMI in front of the barcode.
`zcat R2.fastq.gz | paste - - - - | awk '{print $1" "$2"\n"substr($3,9,8)substr($3,1,8)substr($3,17)"\n"$4"\n"$5}' | pigz -p8 > R2_Alevin.fq.gz`

then, I run Alevin with:
`salmon alevin -lA -i ref_genome/index/ --barcodeLength 8 --umiLength 8 --end 5 -1 fq/R2_Alevin.fq.gz -2 fq/R1.fastq.gz -p 8 --tgMap ref_genome/gencode.vM20.tx2gene.tsv -o alevin_out --dumpUmiGraph --dumpFeatures --dumpCsvCounts --whitelist BC.whitelist`

This seems to work: the library is 47M and the _filtered_cb_frequency.txt_ contains 43M assigned barcodes in total. The _MappedUmi.txt_ contains 18.5M UMIs, fitting perfectly with the reported alignment rate of ~40% (which is relatively low, but OK for this library). Also if I use the `--dumpfq` option, the barcodes and UMIs are nicely attached to the sequencing reads.

Strangely, if I sum the entries in the CSV or binary quant matrix, I get ~3.75M reads. 
 
I was able to run the 10x PBMC4k example and there, the sum of the count matrix entries indeed fitted the reported UMI counts and mapping rate. 

Specifically, please provide at least the following information:

  * Which version of salmon was used?
salmon 0.13.1

  * How was salmon installed (compiled, downloaded executable, through bioconda)?
downloaded executable and bioconda give the same result

  * Which reference (e.g. transcriptome) was used?
mouse gencode vM20 (mm10)

  * Which read files were used?
adapted celseq2 protocol

  * Which program options were used?
See above

**Expected behavior**
I expected a total of 18.5M counts in the quant matrix, where the sums per barcode fit those reported in the _MappedUmi.txt_ Is my assumption that the quant matrix should only contain integers correct?

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 Ubuntu 18.04.1 LTS

**Additional context**

**Comment by k3yavi** [comment] 2019-05-07 13:35
Hi @wmegchel ,

Thanks for the raising the issue.
If I understand correctly, your question is Number of mapped reads != Number of deduplicated reads ? Basically, the quant matrix (and the csv matrix) represents the number of _deduplicated_ reads, which indeed should be less than number of mapped reads. Alevin consumes the reads which are mapped, performs UMI level deduplication and reports them in the `quant_mat.gz`.

I am unsure about the 10x part of your question i.e.
> I was able to run the 10x PBMC4k example and there, the sum of the count matrix entries indeed fitted the reported UMI counts and mapping rate.

If this is true then something is wrong, as the number of mapped reads should be much greater than (based on the number of PCR cycles) number of deduplicated reads.

Hope this answer your question ?

**Comment by wmegchel** [comment] 2019-05-07 14:15
Hi @k3yavi,

Thanks for the reply!

Let's take the PBMC 4K as example. Looking at the summary sheet from 10x: 
http://cf.10xgenomics.com/samples/cell-exp/2.1.0/pbmc4k/pbmc4k_web_summary.html

They detected 4,340 cells with a median UMI count of 3,866 per cell. That means ~17M UMIs in the count matrix, which is in the same order what I find with Alevin. I am not sure if/where Alevin reports the number of mapped reads (maybe it is the number of hits?), but this is not of much importance.

Indeed, the total UMI count  is **much** lower than the number of sequenced/mapped/barcoded reads (~190M), which is expected. However, using the `--dumpUmiGraph` option provides a file "MappedUMI.txt" which I assume are the number of deduplicated UMIs mapped per cell/barcode (summed over all genes). The sum of over all the barcodes = 17M in this case and the sum per barcode = the sum in the quant_mat

This does not hold for the adapted cel-seq2 protocol. sum mapped UMI != summed quant_mat.gz

I am making a mistake, or is there something wrong?

**Comment by k3yavi** [comment] 2019-05-07 14:33
Very strange, I'd like to start with first apologizing for relatively poor documentation for all these meta files (`MappedUMI`) and I think that's the point of confusion. The expected behavior is as follows:
* `--dumpFeature` dumps various meta files like `filtered_cb_frequency.txt` which gives number of reads in each CB after sequence correction and  `MappedUMI,txt` which is a subset of reads from the `filtered_cb_frequency.txt` which are mapped by alevin and should be reflective of the mapping rate.
* `--dumpUmiGraph` dumps the internal graphical structure used by alevin for deduplication.

Having said that, I was curious that the sum of count in the `MappedUMI.txt` is coming out to be 17M. I tested the same at my end and it's coming out to be ~200M . I am puzzled why the counts are so low for your run, can you please double check if alevin has finished ? It seems the behavior you are observing in the CEL-seq data is the right one. For counting the number of mapped reads use the file `MappedUMI.txt` and for counting number of deduplicated reads use `quants_mat.gz`.

**Comment by wmegchel** [comment] 2019-05-07 14:54
Right, that might explain it.

So first of all  I indeed used the `--dumpFeature` option to get the `MappedUMI.txt`, sorry for that. I will check the file once again and rerun the analysis, which I did on my machine at home. It might be that the 17M I told from the top of my head is actually incorrect.  Unfortunately, the 10x crashes with a memory error on our clusters (I tested 2 different machines), for which I will open a separate thread (I think I saw someone else reporting a similar issue; will look that up). Celseq2 runs fine.

I will check the analysis and the `mappedUMI.txt` a.s.a.p. I fear this issue will soon be resolved where both of us have a memory problem to deal with ;-)

Cheers,
Wout 

 

e again, but strangely I can only run the 10X on my home PC, on our cluster it returns a memory error,  I will open a separate thread for that.

**Comment by k3yavi** [comment] 2019-05-07 15:01
That sounds great. Yea the memory problem is one of the problem which we were not able to resolve in the past as it was very hard to replicate. The conclusion last time was it's because of some cluster level restrictions however the experiments runs fine on a local comp. Either way do let us know how it turns out for you. Glad to help.

**Comment by k3yavi** [comment] 2019-06-02 15:20
Hi @wmegchel ,

We have just release `v0.14.0`, we expect the memory problem to go away with the latest release. Let us know if it works out for you and feel free to close the issue.

**Comment by k3yavi** [comment] 2019-11-01 00:09
Closing due to inactivity, feel free to reopen if you face any problems.

**Closed by k3yavi** 2019-11-01 00:09 UTC
Labels: alevin, question
