### ISSUE TITLE
quant Exception : [Failed to read 130159192 bytes from input stream! Read 65079596]

### ISSUE THREAD

**Issue by ppflrs** [COMBINE-lab/salmon#129] opened 2017-03-16 17:21 UTC
Hello all, we are trying to use salmon quant on environmental samples using a big index but the quant step keeps crashing. While trying to quant different samples all crashed at the same step with the error message: `Exception : [Failed to read 130159192 bytes from input stream! Read 65079596]`

The system is part of a cluster and we have requested 500gb of RAM and disk available for the job and I kept track of the memory and disk usage which never exceeded 254gb.

lsb_release -a
```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	Scientific
Description:	Scientific Linux release 6.4 (Carbon)
Release:	6.4
Codename:	Carbon
```

Do you have any idea what can be the causing the error?

Thanks

We are using the precompiled salmon bin and running it with:

`salmon quant -i $index -1 $f1 -2 $f2 -o $output_folder --meta --incompatPrior 0.0 --libType A -p 8 --gcBias --seqBias --numBootstraps 30`

```
Version Info: This is the most recent version of Salmon.
### salmon (mapping-based) v0.8.1
### [ program ] => salmon 
### [ command ] => quant 
### [ index ] => { ./storage/tmm.idx }
### [ mates1 ] => { DNA_1.fastq.gz }
### [ mates2 ] => {DNA_2.fastq.gz }
### [ output ] => { /DNA_tmm }
### [ meta ] => { }
### [ incompatPrior ] => { 0.0 }
### [ libType ] => { A }
### [ threads ] => { 8 }
### [ gcBias ] => { }
### [ seqBias ] => { }
### [ numBootstraps ] => { 30 }
Logs will be written to ./storage/logs
[2017-03-15 11:53:20.568] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2017-03-15 11:53:20.568] [jointLog] [info] parsing read library format
[2017-03-15 11:53:20.568] [jointLog] [info] There is 1 library.
[2017-03-15 11:53:20.653] [jointLog] [info] Loading Quasi index
[2017-03-15 11:53:20.683] [jointLog] [info] Loading 64-bit quasi index
[2017-03-15 11:53:20.684] [stderrLog] [info] Loading Suffix Array 
[2017-03-15 12:19:05.982] [stderrLog] [info] Loading Transcript Info 
Exception : [Failed to read 130159192 bytes from input stream! Read 65079596]
salmon quant was invoked improperly.
For usage information, try salmon quant --help
Exiting.
```

Index building log:

```
Version Info: This is the most recent version of Salmon.
index [" ./storage/tmm.idx"] did not previously exist  . . . creating it
[2017-03-14 12:10:34.791] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 30000 transcripts[2017-03-14 12:10:36.701] [jointLog] [warning] Entry with header [734bf21190b56e1ed4c8d7093c340df1fc6266bd80ed60ebc0ae0f4e9343c3a4], had length less than the k-mer length of 31 (perhaps after poly-A clipping)
counted k-mers for 420000 transcripts[2017-03-14 12:10:56.697] [jointLog] [warning] Entry with header [0c9d699aa70741734115dadd8175a44a013ad4122a3af7952e3b38e9593da047], had length less than the k-mer length of 31 (perhaps after poly-A clipping)
counted k-mers for 11130000 transcripts[2017-03-14 12:20:15.975] [jointLog] [warning] Entry with header [9067b76fbcadd65a043ddff42dccfbd201e1b7ab5307ce7712d6301e32923ff1], had length less than the k-mer length of 31 (perhaps after poly-A clipping)
[2017-03-14 12:20:15.975] [jointLog] [warning] Entry with header [98095e437f311b64c902b3ec0c2d0310d626e1d74e7ad46c0cae049006296647], had length less than the k-mer length of 31 (perhaps after poly-A clipping)
counted k-mers for 16260000 transcriptsElapsed time: 840.275s

Replaced 257168 non-ATCG nucleotides
Clipped poly-A tails from 11 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 15.7997s
Writing sequence data to file . . . done
Elapsed time: 140.642s
[info] Building 64-bit suffix array (length of generalized text is 15197332366 )
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 1040.1s
done
Elapsed time: 5084.83s
processed 15197000000 positions
khash had 3470062382 keys
saving hash to disk . . . done
Elapsed time: 713.385s
[2017-03-14 15:50:05.359] [jLog] [info] done building index
```

**Comment by rob-p** [comment] 2017-03-16 17:25
Hi @ppflrs,

  Thanks for the detailed bug report.  It seems that the index was constructed properly, but is not being appropriately read in during the quant phase.  I've seen a big-index issue with 0.8.1 from another user as well --- but I haven't had a chance to dig down into this yet.  Would it be possible for you to see if the issue also exists if you try the precompiled executable for v0.7.2?  If that index builds and runs for you, we can at least narrow down the error to this particular release.

Thanks,
Rob

**Comment by rob-p** [comment] 2017-03-16 17:58
Interestingly, 130159192 = 2 * 65079596, so it looks like there is probably some place it is expecting to read 64-bit integers but it's seeing 32-bit integers (no need to respond to this comment, I'm just musing out lout here).

**Comment by rob-p** [comment] 2017-03-17 01:18
I'm trying to reproduce this issue, but I'm having trouble triggering it.  Do you have any smaller examples (reference) where you see this behavior?

**Comment by rob-p** [comment] 2017-03-17 03:15
The specific error message seems to be coming from [the serialization library we use](https://github.com/USCiLab/cereal/blob/master/include/cereal/archives/portable_binary.hpp#L245).  This was upgraded recently, so I'm hoping that they didn't introduce a new bug upstream.  As soon as I can reproduce this, I can test if rolling back the version of the serialization library fixes the issue (which I don't believe occurred in 0.7.2).

**Comment by rob-p** [comment] 2017-03-17 13:07
OK --- I have an example where I can reproduce, and it does indeed seem to only occur with 64-bit indices.  I will try and track this down ASAP, I'm almost certain it has to do with cereal though.

**Comment by rob-p** [comment] 2017-03-17 18:12
Ok, I've tracked down and fixed the bug.  I'll be tagging a new release with the fix soon.  I'll ping back here and close this issue when the new release is out.

**Comment by rob-p** [comment] 2017-03-17 20:17
@ppflrs 

  This issue is now resolved in [v0.8.2](https://github.com/COMBINE-lab/salmon/releases/tag/v0.8.2).  Further, since the bug was only on the de-serialization end, this should work with the index you've already prepared with Salmon v0.8.1.  Please let me know if that works for you.

--Rob

**Closed by rob-p** 2017-03-17 20:17 UTC

**Comment by ppflrs** [comment] 2017-03-19 13:51
@rob-p Thanks! We will try the new version and let you know if it works.

**Comment by ppflrs** [comment] 2017-03-23 10:19
Hi @rob-p 

Sorry, but we couldn't test again the index I used to report the issue.

Instead, we used a smaller one with the following characteristics:

```
counted k-mers for 16040000 transcripts
Elapsed time: 726.738s

Replaced 5730782 non-ATCG nucleotides
Clipped poly-A tails from 530 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 13.1116s
Writing sequence data to file . . . done
Elapsed time: 118.505s
[info] Building 64-bit suffix array (length of generalized text is 12671064288 )
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 877.586s
done
Elapsed time: 3607.17s
processed 12671000000 positions
khash had 5905993560 keys
saving hash to disk . . . done
Elapsed time: 1249.59s
[2017-03-22 06:39:06.131] [jLog] [info] done building index
```

Using this new index and salmon v0.8.2 precompiled binaries we didn't have any problems.

Hope this helps.

Thanks!
