### ISSUE TITLE
alevin featuredump output

### ISSUE THREAD

**Issue by shivagit123** [COMBINE-lab/salmon#413] opened 2019-08-05 23:21 UTC
Hi,
Do you have documentation explaining the featuredump output txt file ?
The output here attached contains more columns than their headers. So bit confusing to interpret the results.
I've attached the featuredump output txt file for your reference.
Can you please explain the columns or point me to the relevant documentation explaining the same.

Shiva
[featureDump.txt](https://github.com/COMBINE-lab/salmon/files/3469696/featureDump.txt)

**Comment by k3yavi** [comment] 2019-08-05 23:57
HI @shivagit123 ,

Thanks for bringing this to our attention, I think there is a bug in writing the header of the txt file.
Here was the expected behavior:
1) If `--dumpUmiGraph` is _not_ provided then we expect total fixed 12 columns which are
```
CB	CorrectedReads	MappedReads	DeduplicatedReads	MappingRate	DedupRate	MeanByMax	NumGenesExpressed	NumGenesOverMean	mRnaFraction	rRnaFraction	ArborescenceCount
```
Unfortunately it seems the expected value from the last (12th) `ArborescenceCount` is getting dumped at 10th position in that case the header should be (but not currently is):
```
CB	CorrectedReads	MappedReads	DeduplicatedReads	MappingRate	DedupRate	MeanByMax	NumGenesExpressed	NumGenesOverMean	ArborescenceCount	mRnaFraction	rRnaFraction
```

2.) if `--dumpUmiGraph` is provided (I am assuming you are) then instead we were experimenting with another feature which follows the convention `<Number of Reads in an Arborescence>:<Frequency of these Arborescences>` i.e. if in a cell X we observe 3 Arborescence each with 2,3,4 number of reads respectively in them then the entry of `ArborescenceCount` should look like `2:1	3:1	4:1`. Since just like the problem with 1) above there seems to be switch of the column 12 to 10 and you are observing weird looking file. 

In short: Everything is fine till column 9th but there is a bug which makes column 12 to 10, 10 to 11 and 11 to 12. If you provide `--dumpUmiGraph` then last two columns represents `mRnaFraction	rRnaFraction` while everything in between column 9th and before last two represents `ArborescenceCount` with special frequency dump as defined above.

My apologies for the trouble I just pushed a fix into the develop branch. However, we have significant other changes in develop branch too so recompilation might make your current index incompatible to `0.14.1` so if you don't wan't to reindex the reference then I'd not recompile from develop and the bugfix will available from the next version.

Solution: The easiest solution is to remove `--dumpUMIgraph` if you don't need the flag and rerun then the only thing to handle is just change the header names. If rerunning alevin is too much work then I can forward you a python parser which can temporary handle the parsing.

**Comment by shivagit123** [comment] 2019-08-06 00:05
Thanks for your quick reply,
It would be great if you can provide the parser . 
I don't think so I can afford to re-run again.

Shiva

**Comment by k3yavi** [comment] 2019-08-06 00:07
Sure, May I know which columns you actually need for the analysis ? Basically are you planning to use `ArborescenceCount` feature for your analysis ?

**Comment by k3yavi** [comment] 2019-08-06 00:17
The following awk script should get rid of `ArborescenceCount` related columns:
```
awk '{for (i=1;i<=NF;i++) {if ((i<=9) || (i>=NF-1) ) printf("%s\t", $i)}; printf("\n") }' featureDump.txt > f1.txt
```

However you have to explicitly change the first line header to:
```
CB	CorrectedReads	MappedReads	DeduplicatedReads	MappingRate	DedupRate	MeanByMax	NumGenesExpressed	NumGenesOverMean	mRnaFraction	rRnaFraction
```

Hope it helps !

**Comment by shivagit123** [comment] 2019-08-06 00:24
Thanks

**Comment by k3yavi** [comment] 2019-10-31 23:58
It's now fixed in latest stable release, closing the issue but feel free to reopen if you have any issues.

**Closed by k3yavi** 2019-10-31 23:58 UTC
Labels: alevin, bug, fixed in develop
