### ISSUE TITLE
similar mapping rate for all samples, and similar quant.sf for all genes across samples

### ISSUE THREAD

**Issue by asher1234** [COMBINE-lab/salmon#346] opened 2019-03-04 03:23 UTC
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
related to salmon

**Describe the bug**
I've been using the Salmon-tximport-DESEq2 pipeline for quite a while now but it's the first time I got similar results from Salmon across samples. I've got 24 samples in total (4 rice genotypes, 2-time point for bacterial blight infection, and 3 replications).

However, this from the raw sequencing data and even the trimmed reads that I used, I've got similar mapping rates across all samples. Similar length, TPM, and NumReads across all genes for all genes. Though the value for each gene differs in the abovementioned parameters. The EffectiveLength though is 250 for all genes across all samples. I've used all four different versions of Salmon as listed below but I'm still getting the same similar mapping rate and the parameters at quant.sf though the values differ a bit from each Salmon version

**To Reproduce**
### Steps and data to reproduce the behavior: for version 0.8

**First I took the genome fasta file and the gff3 file and made a transcriptome fasta file using Salmon:**
module load Cufflinks/2.2.1
gffread all.gff3 -g all.chrs.fasta -w MSU7_transcript.fasta

**I then indexed the transcript fasta file.**
#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=50G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J index_Salmon

module load Salmon/0.8.2-IGB-gcc-4.9.4-Python-2.7.13

salmon index -t ~/data/genome/MSU7_transcript.fasta -i ~/data/genome/MSU7_transcript.index --type quasi -k 31

**I then run transcript abundance estimate pipeline for the raw-reads and the trimmed reads as follows:**
#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.8.2-IGB-gcc-4.9.4-Python-2.7.13

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7_transcript.index -l A \
-1 ~/data/raw-data/BLB/${line}1.fastq.gz \
-2 ~/data/raw-data/BLB/${line}2.fastq.gz --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_Sheng_old/${line} --seqBias --gcBias

#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.8.2-IGB-gcc-4.9.4-Python-2.7.13

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7_transcript.index -l A \
-1 ~/results/trimmingSheng/${line}1.paired.fastq \
-2 ~/results/trimmingSheng/${line}2.paired.fastq --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_Sheng_new/${line} --seqBias --gcBias

**Steps and data to reproduce the behavior: for version 0.12**
module load Cufflinks/2.2.1
gffread MSU7_all.gff3 -g all.chrs.fasta -w MSU7_newtranscript.fasta

#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=50G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J index_Salmon

module load Salmon/0.12.0-IGB-gcc-8.2.0

salmon index -t ~/data/genome/MSU7_newtranscript.fasta -i ~/data/genome/MSU7new_transcript.index --type quasi -k 31

#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.12.0-IGB-gcc-8.2.0

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7new_transcript.index -l A \
-1 ~/data/raw-data/BLB/${line}1.fastq.gz \
-2 ~/data/raw-data/BLB/${line}2.fastq.gz --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_BLB/${line} --seqBias --gcBias --validateMappings

#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.12.0-IGB-gcc-8.2.0

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7new_transcript.index -l A \
-1 ~/results/trimmingSheng/${line}1.paired.fastq \
-2 ~/results/trimmingSheng/${line}2.paired.fastq --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_Sheng_new/${line} --seqBias --gcBias --validateMappings

Specifically, please provide at least the following information:

  * Which version of salmon was used?
   Salmon/0.8.2-IGB-gcc-4.9.4-Python-2.7.13    Salmon/0.11.3-IGB-gcc-4.9.4
   Salmon/0.9.1-IGB-gcc-4.9.4                  Salmon/0.12.0-IGB-gcc-8.2.0 (D)

  * How was salmon installed (compiled, downloaded executable, through bioconda)?
through the biocluster in the University

  * Which reference (e.g. transcriptome) was used?
converted the genomic fasta file to transcriptomic fasta file (described above)
 
  * Which read files were used?
the raw sequencing reads and the trimmed reads from the paired-end data

  * Which which program options were used?
described above

**Expected behavior**

I've used the quassi mapping of Salmon using different versions several times and I expect to get different mapping rate per sample. I also expect to get different values of the parameters in the quant.sf parameters across all genes and across samples.
 

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

### For version 0.8. This is similar across all samples:
Name    Length  EffectiveLength TPM     NumReads
LOC_Os01g01010.1        3017    250     28.8836 527.392
LOC_Os01g01010.2        2218    250     1.84062 33.6083
LOC_Os01g01019.1        1127    250     0.0547668       1
LOC_Os01g01030.1        2464    250     4.43611 81
LOC_Os01g01040.4        1524    250     0.941635        17.1935
LOC_Os01g01040.1        2508    250     11.5632 211.135
LOC_Os01g01040.2        2482    250     8.02081 146.454
LOC_Os01g01040.3        2583    250     8.55554 156.218
LOC_Os01g01050.1        2039    250     17.2333 314.667

### The counted total reads, observed total fragments, and the mapping rate is similar for all samples for both the raw-dat and the trimmed reads.
[2019-03-03 06:29:53.168] [jointLog] [info] parsing read library format
[2019-03-03 06:29:53.168] [jointLog] [info] There is 1 library.
[2019-03-03 06:29:53.224] [jointLog] [info] Loading Quasi index
[2019-03-03 06:29:53.224] [jointLog] [info] Loading 32-bit quasi index
[2019-03-03 06:30:02.239] [jointLog] [info] done
[2019-03-03 06:30:02.239] [jointLog] [info] Index contained 66153 targets
[2019-03-03 06:30:03.414] [jointLog] [info] Automatically detected most likely library type as MU
[2019-03-03 06:31:37.523] [fileLog] [info]
At end of round 0
==================
Observed 18861231 total fragments (18861231 in most recent round)

[2019-03-03 06:31:37.522] [jointLog] [info] Computed 48502 rich equivalence classes for further processing
[2019-03-03 06:31:37.522] [jointLog] [info] Counted 17308442 total reads in the equivalence classes
[2019-03-03 06:31:37.528] [jointLog] [info] Mapping rate = 91.7673%

[2019-03-03 06:31:37.528] [jointLog] [info] finished quantifyLibrary()

### For version 0.12. This is similar across all samples:

Name    Length  EffectiveLength TPM     NumReads
LOC_Os01g01010.1        3017    250.000 30.539503       527.399
LOC_Os01g01010.2        2218    250.000 1.714089        29.601
LOC_Os01g01019.1        1127    250.000 0.057906        1.000
LOC_Os01g01030.1        2464    250.000 4.632473        80.000
LOC_Os01g01040.4        1524    250.000 0.842494        14.549
LOC_Os01g01040.1        2508    250.000 12.017881       207.542
LOC_Os01g01040.2        2482    250.000 8.005651        138.253
LOC_Os01g01040.3        2583    250.000 9.187142        158.656
LOC_Os01g01050.1        2039    250.000 21.476314       370.883

[2019-03-03 07:14:59.272] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-03-03 07:14:59.272] [jointLog] [info] Usage of --validateMappings implies use of minScoreFraction. Since not explicitly specified, it is being set to 0.65
[2019-03-03 07:14:59.272] [jointLog] [info] Usage of --validateMappings implies use of range factorization. rangeFactorizationBins is being set to 4
[2019-03-03 07:14:59.272] [jointLog] [info] Usage of --validateMappings implies a default consensus slack of 1. Setting consensusSlack to 1.
[2019-03-03 07:14:59.272] [jointLog] [info] parsing read library format
[2019-03-03 07:14:59.272] [jointLog] [info] There is 1 library.
[2019-03-03 07:14:59.329] [jointLog] [info] Loading Quasi index
[2019-03-03 07:14:59.329] [jointLog] [info] Loading 32-bit quasi index
[2019-03-03 07:15:12.564] [jointLog] [info] done
[2019-03-03 07:15:12.564] [jointLog] [info] Index contained 66,004 targets
[2019-03-03 07:15:14.824] [jointLog] [info] Automatically detected most likely library type as MU
[2019-03-03 07:16:36.263] [jointLog] [info] Thread saw mini-batch with a maximum of 89.90% zero probability fragments
[2019-03-03 07:16:36.295] [jointLog] [info] Thread saw mini-batch with a maximum of 89.70% zero probability fragments
[2019-03-03 07:16:36.305] [jointLog] [info] Thread saw mini-batch with a maximum of 88.36% zero probability fragments
[2019-03-03 07:16:36.311] [jointLog] [info] Thread saw mini-batch with a maximum of 90.16% zero probability fragments
[2019-03-03 07:16:36.341] [jointLog] [info] Thread saw mini-batch with a maximum of 26.54% zero probability fragments
[2019-03-03 07:16:36.391] [jointLog] [info] Computed 58,867 rich equivalence classes for further processing
[2019-03-03 07:16:36.391] [jointLog] [info] Counted 16,837,807 total reads in the equivalence classes
[2019-03-03 07:16:36.402] [jointLog] [warning] 0.00371007% of fragments were shorter than the k used to build the index (31).
If this fraction is too large, consider re-building the index with a smaller k.
The minimum read size found was 30.

[2019-03-03 07:16:36.402] [jointLog] [info] Mapping rate = 89.242%

[2019-03-03 07:16:36.402] [jointLog] [info] finished quantifyLibrary()

The EffectiveLength of all genes is the same for all genes regardless of the version and data used.

**Desktop** (please complete the following information):

OS: Windows 7 Enterprise
Version: Intel (R) Core(TM) i5-4200U CPU (a) 1.60GHz 2.30 GHz
4.00 GB RAM
System: 64-bit Operating system 

**Additional context**
I've used the same laptop computer and the same codes as before (just changing the data and the path for the directories)

**Comment by rob-p** [comment] 2019-03-04 03:44
Hi @asher1234,

  Thanks for the detailed bug report.  The detection of the library type as `MU` certainly does raise some flags as that is not something that would be expected.  Moreover, in the v0.12.0 log you posted, we see messages like:

```
Thread saw mini-batch with a maximum of 90.16% zero probability fragments
```

Which means that e.g. ~90% of the fragments, even though they map, are being assigned a 0 probability under the model (because of e.g. incompatibility with the library type).  Would you be able to share one of these samples and the reference transcriptome against which you are quantifying?  Also, do things look any different if you force the library type to be something more common (e.g. `-l IU`)?

--Rob

**Comment by asher1234** [comment] 2019-03-04 11:13
Hi Rob,

Appreciate the response. 

The link for the data should be in here:
https://drive.google.com/open?id=1SDqMrHLx-cbfvD4HDmpxcHitqO3B1ZLR
[https://drive.google.com/open?id=1SDqMrHLx-cbfvD4HDmpxcHitqO3B1ZLR](url)
https://drive.google.com/drive/folders/1SDqMrHLx-cbfvD4HDmpxcHitqO3B1ZLR?usp=sharing

I've tried forcing the library type for both version 0.8 and 0.12 as follows:

**For version 0.8 with raw reads**
#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.8.2-IGB-gcc-4.9.4-Python-2.7.13

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7_transcript.index -l IU \
-1 ~/data/raw-data/BLB/${line}1.fastq.gz \
-2 ~/data/raw-data/BLB/${line}2.fastq.gz --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_Sheng_IU_old/${line} --seqBias --gcBias

The EffectiveLength is again the same (250) for all genes across all samples:
Name    Length  EffectiveLength TPM     NumReads
LOC_Os01g01010.1        3017    250     28.8836 527.392
LOC_Os01g01010.2        2218    250     1.84062 33.6083
LOC_Os01g01019.1        1127    250     0.0547668       1
LOC_Os01g01030.1        2464    250     4.43611 81
LOC_Os01g01040.4        1524    250     0.941635        17.1935
LOC_Os01g01040.1        2508    250     11.5632 211.135
LOC_Os01g01040.2        2482    250     8.02082 146.454
LOC_Os01g01040.3        2583    250     8.55554 156.218
LOC_Os01g01050.1        2039    250     17.2333 314.667

The mapping rate is again similar for all samples:
[2019-03-04 04:42:18.872] [jointLog] [info] parsing read library format
[2019-03-04 04:42:18.872] [jointLog] [info] There is 1 library.
[2019-03-04 04:42:18.928] [jointLog] [info] Loading Quasi index
[2019-03-04 04:42:18.929] [jointLog] [info] Loading 32-bit quasi index
[2019-03-04 04:42:28.958] [jointLog] [info] done
[2019-03-04 04:42:28.958] [jointLog] [info] Index contained 66153 targets
[2019-03-04 04:44:08.443] [fileLog] [info]
At end of round 0
==================
Observed 18861231 total fragments (18861231 in most recent round)

[2019-03-04 04:44:08.442] [jointLog] [info] Computed 48502 rich equivalence classes for further processing
[2019-03-04 04:44:08.442] [jointLog] [info] Counted 17308442 total reads in the equivalence classes
[2019-03-04 04:44:08.450] [jointLog] [info] Mapping rate = 91.7673%

[2019-03-04 04:44:08.450] [jointLog] [info] finished quantifyLibrary()


**For version 0.12**
#!/bin/bash
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=10G
#SBATCH --mail-use=tarun2@illinois.edu
#SBATCH -J Salmon
#SBATCH -a 1-24

module load Salmon/0.12.0-IGB-gcc-8.2.0

line=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" ~/source/BLBnew.txt)

salmon quant -i ~/data/genome/MSU7new_transcript.index -l IU \
-1 ~/results/trimmingSheng/${line}1.paired.fastq \
-2 ~/results/trimmingSheng/${line}2.paired.fastq --numBootstraps=30 \
-p 12 -o ~/results/salmon_quant_Sheng_IU/${line} --seqBias --gcBias --validateMappings

There are no estimate and reads generated when invokin the library type IU:
Name    Length  EffectiveLength TPM     NumReads
LOC_Os01g01010.1        3017    3017.000        0.000000        0.000
LOC_Os01g01010.2        2218    2218.000        0.000000        0.000
LOC_Os01g01019.1        1127    1127.000        0.000000        0.000
LOC_Os01g01030.1        2464    2464.000        0.000000        0.000
LOC_Os01g01040.4        1524    1524.000        0.000000        0.000
LOC_Os01g01040.1        2508    2508.000        0.000000        0.000
LOC_Os01g01040.2        2482    2482.000        0.000000        0.000
LOC_Os01g01040.3        2583    2583.000        0.000000        0.000
LOC_Os01g01050.1        2039    2039.000        0.000000        0.000

[2019-03-04 01:24:12.788] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2019-03-04 01:24:12.788] [jointLog] [info] Usage of --validateMappings implies use of minScoreFraction. Since not explicitly specified, it is being set to 0.65
[2019-03-04 01:24:12.788] [jointLog] [info] Usage of --validateMappings implies use of range factorization. rangeFactorizationBins is being set to 4
[2019-03-04 01:24:12.788] [jointLog] [info] Usage of --validateMappings implies a default consensus slack of 1. Setting consensusSlack to 1.
[2019-03-04 01:24:12.788] [jointLog] [info] parsing read library format
[2019-03-04 01:24:12.788] [jointLog] [info] There is 1 library.
[2019-03-04 01:24:12.852] [jointLog] [info] Loading Quasi index
[2019-03-04 01:24:12.852] [jointLog] [info] Loading 32-bit quasi index
[2019-03-04 01:24:19.703] [jointLog] [info] done
[2019-03-04 01:24:19.704] [jointLog] [info] Index contained 66,004 targets
[2019-03-04 01:25:14.064] [jointLog] [info] Thread saw mini-batch with a maximum of 91.10% zero probability fragments
[2019-03-04 01:25:14.075] [jointLog] [info] Thread saw mini-batch with a maximum of 90.58% zero probability fragments
[2019-03-04 01:25:14.085] [jointLog] [info] Thread saw mini-batch with a maximum of 90.64% zero probability fragments
[2019-03-04 01:25:14.089] [jointLog] [info] Thread saw mini-batch with a maximum of 91.08% zero probability fragments
[2019-03-04 01:25:14.091] [jointLog] [info] Thread saw mini-batch with a maximum of 90.72% zero probability fragments
[2019-03-04 01:25:14.093] [jointLog] [info] Thread saw mini-batch with a maximum of 90.78% zero probability fragments
[2019-03-04 01:25:14.102] [jointLog] [info] Thread saw mini-batch with a maximum of 90.60% zero probability fragments
[2019-03-04 01:25:14.102] [jointLog] [info] Thread saw mini-batch with a maximum of 90.38% zero probability fragments
[2019-03-04 01:25:14.104] [jointLog] [info] Thread saw mini-batch with a maximum of 90.44% zero probability fragments
[2019-03-04 01:25:14.106] [jointLog] [info] Thread saw mini-batch with a maximum of 90.64% zero probability fragments
[2019-03-04 01:25:14.117] [jointLog] [info] Thread saw mini-batch with a maximum of 90.60% zero probability fragments
[2019-03-04 01:25:14.129] [jointLog] [info] Thread saw mini-batch with a maximum of 90.66% zero probability fragments
[2019-03-04 01:25:14.173] [jointLog] [warning] salmon was only able to assign 0 fragments to transcripts in the index, but the minimum number of required assigned fragments (--minAssignedFrags) was 10. This could be indicative of a mismatch between the reference and sample, or a very bad sample.  You can change the --minAssignedFrags parameter to force salmon to quantify with fewer assigned fragments (must have at least 1).


Please advise.

Sincerely,
Asher

**Comment by rob-p** [comment] 2019-03-04 20:39
Hi @asher1234,

  Thanks.  I'll try and grab the data now.  The 0.12.0 log here is quite informative.  It looks like the problem is that none of the reads are making through the likelihood filter, which explains why you see the output you do.  I'll take a look and see if there is a clear reason why.

--Rob

**Comment by rob-p** [comment] 2019-03-05 01:46
Hi @asher1234,

  So, indeed the paired-end reads do not map to the transcriptome you provided.  I tried mapping them as unpaired reads, and they map much better.  Looking into the actual files, it appears that your left and right read files are _identical_!  The SHA sums e.g. are exactly the same:

```
rob@newton:~/salmon/build$ sha256sum BLB/T2_5-2_1.fastq.gz
874bca43c918acbed3e3279434c650a187fb15db151fc871ecfb6406db951040  BLB/T2_5-2_1.fastq.gz
rob@newton:~/salmon/build$ sha256sum BLB/T2_5-2_2.fastq.gz
874bca43c918acbed3e3279434c650a187fb15db151fc871ecfb6406db951040  BLB/T2_5-2_2.fastq.gz
```

So, these reads don't make any sense as paired-end reads, since all of the fragments are degenerate.  Are you sure the files weren't mixed up or overwritten in some way?

--Rob

**Comment by rob-p** [comment] 2019-03-14 01:33
Hi @asher1234,

  Given that the reads are the same, it seems the issue here is the input rather than the behavior of salmon.  So, I'm closing this issue.  Please re-open if you observe similar behavior on properly paired files.

**Closed by rob-p** 2019-03-14 01:33 UTC
